export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <main className="flex-grow flex items-center justify-center">
        {children}
      </main>
    </>
  );
}
